name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 12.10.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.10.0

      - name: Install and Lint
        run: |
          npm ci
          npm run lint
        env:
          NODE_ENV: development
          CI: true

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@2.0.0
        env:
          NODE_ENV: development
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: npm ci && npm run build
