name: CI

on: push

jobs:
  test-build-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.10.0

      - name: Install
        run: npm ci
        env:
          NODE_ENV: development
          CI: true

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@2.0.0
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CNAME: mattcowley.co.uk
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: build
